/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as SearchRouteImport } from './routes/search'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as DevComponentsRouteImport } from './routes/dev/components'
import { Route as DevShopifyHealthRouteImport } from './routes/dev/shopify-health'
import { Route as ProductSkuRouteImport } from './routes/product/$sku'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const DevShopifyHealthRoute = DevShopifyHealthRouteImport.update({
  id: '/dev/shopify-health',
  path: '/dev/shopify-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSkuRoute = ProductSkuRouteImport.update({
  id: '/product/$sku',
  path: '/product/$sku',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/shopify-health': typeof DevShopifyHealthRoute
  '/product/$sku': typeof ProductSkuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/shopify-health': typeof DevShopifyHealthRoute
  '/product/$sku': typeof ProductSkuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRoute
  '/search': typeof SearchRoute
  '/category/$slug': typeof CategorySlugRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/shopify-health': typeof DevShopifyHealthRoute
  '/product/$sku': typeof ProductSkuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/search'
    | '/category/$slug'
    | '/dev/components'
    | '/dev/shopify-health'
    | '/product/$sku'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/search'
    | '/category/$slug'
    | '/dev/components'
    | '/dev/shopify-health'
    | '/product/$sku'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/search'
    | '/category/$slug'
    | '/dev/components'
    | '/dev/shopify-health'
    | '/product/$sku'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRoute
  SearchRoute: typeof SearchRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DevComponentsRoute: typeof DevComponentsRoute
  DevShopifyHealthRoute: typeof DevShopifyHealthRoute
  ProductSkuRoute: typeof ProductSkuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/shopify-health': {
      id: '/dev/shopify-health'
      path: '/dev/shopify-health'
      fullPath: '/dev/shopify-health'
      preLoaderRoute: typeof DevShopifyHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$sku': {
      id: '/product/$sku'
      path: '/product/$sku'
      fullPath: '/product/$sku'
      preLoaderRoute: typeof ProductSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRoute,
  SearchRoute: SearchRoute,
  CategorySlugRoute: CategorySlugRoute,
  DevComponentsRoute: DevComponentsRoute,
  DevShopifyHealthRoute: DevShopifyHealthRoute,
  ProductSkuRoute: ProductSkuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
