/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as BulkOrderRouteImport } from './routes/bulk-order'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as OrderSubmittedRouteImport } from './routes/order-submitted'
import { Route as PreviewAccessRouteImport } from './routes/preview-access'
import { Route as QuoteSubmittedRouteImport } from './routes/quote-submitted'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as AccountPricingRouteImport } from './routes/account/pricing'
import { Route as AccountUsersRouteImport } from './routes/account/users'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as CheckoutIdRouteImport } from './routes/checkout/$id'
import { Route as DevComponentsRouteImport } from './routes/dev/components'
import { Route as DevFixtureShopifyLoginRouteImport } from './routes/dev/fixture-shopify-login'
import { Route as DevShopifyHealthRouteImport } from './routes/dev/shopify-health'
import { Route as OrderIdRouteImport } from './routes/order/$id'
import { Route as ProductSkuRouteImport } from './routes/product/$sku'
import { Route as QuoteIndexRouteImport } from './routes/quote/index'
import { Route as QuoteIdRouteImport } from './routes/quote/$id'
import { Route as StaffOrdersRouteImport } from './routes/staff/orders'
import { Route as StaffQuotesRouteImport } from './routes/staff/quotes'
import { Route as StaffOrderIdRouteImport } from './routes/staff/order/$id'
import { Route as StaffQuoteIdRouteImport } from './routes/staff/quote/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOrderRoute = BulkOrderRouteImport.update({
  id: '/bulk-order',
  path: '/bulk-order',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSubmittedRoute = OrderSubmittedRouteImport.update({
  id: '/order-submitted',
  path: '/order-submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewAccessRoute = PreviewAccessRouteImport.update({
  id: '/preview-access',
  path: '/preview-access',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteSubmittedRoute = QuoteSubmittedRouteImport.update({
  id: '/quote-submitted',
  path: '/quote-submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountPricingRoute = AccountPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountUsersRoute = AccountUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AccountRouteRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFixtureShopifyLoginRoute = DevFixtureShopifyLoginRouteImport.update({
  id: '/dev/fixture-shopify-login',
  path: '/dev/fixture-shopify-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevShopifyHealthRoute = DevShopifyHealthRouteImport.update({
  id: '/dev/shopify-health',
  path: '/dev/shopify-health',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSkuRoute = ProductSkuRouteImport.update({
  id: '/product/$sku',
  path: '/product/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIndexRoute = QuoteIndexRouteImport.update({
  id: '/quote/',
  path: '/quote/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIdRoute = QuoteIdRouteImport.update({
  id: '/quote/$id',
  path: '/quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffOrdersRoute = StaffOrdersRouteImport.update({
  id: '/staff/orders',
  path: '/staff/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffQuotesRoute = StaffQuotesRouteImport.update({
  id: '/staff/quotes',
  path: '/staff/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffOrderIdRoute = StaffOrderIdRouteImport.update({
  id: '/staff/order/$id',
  path: '/staff/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffQuoteIdRoute = StaffQuoteIdRouteImport.update({
  id: '/staff/quote/$id',
  path: '/staff/quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/basket': typeof BasketRoute
  '/bulk-order': typeof BulkOrderRoute
  '/categories': typeof CategoriesRoute
  '/order-submitted': typeof OrderSubmittedRoute
  '/preview-access': typeof PreviewAccessRoute
  '/quote-submitted': typeof QuoteSubmittedRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/staff-login': typeof StaffLoginRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/pricing': typeof AccountPricingRoute
  '/account/users': typeof AccountUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/fixture-shopify-login': typeof DevFixtureShopifyLoginRoute
  '/dev/shopify-health': typeof DevShopifyHealthRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$sku': typeof ProductSkuRoute
  '/quote/$id': typeof QuoteIdRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/quotes': typeof StaffQuotesRoute
  '/account/': typeof AccountIndexRoute
  '/quote/': typeof QuoteIndexRoute
  '/staff/order/$id': typeof StaffOrderIdRoute
  '/staff/quote/$id': typeof StaffQuoteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/basket': typeof BasketRoute
  '/bulk-order': typeof BulkOrderRoute
  '/categories': typeof CategoriesRoute
  '/order-submitted': typeof OrderSubmittedRoute
  '/preview-access': typeof PreviewAccessRoute
  '/quote-submitted': typeof QuoteSubmittedRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/staff-login': typeof StaffLoginRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/pricing': typeof AccountPricingRoute
  '/account/users': typeof AccountUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/fixture-shopify-login': typeof DevFixtureShopifyLoginRoute
  '/dev/shopify-health': typeof DevShopifyHealthRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$sku': typeof ProductSkuRoute
  '/quote/$id': typeof QuoteIdRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/quotes': typeof StaffQuotesRoute
  '/account': typeof AccountIndexRoute
  '/quote': typeof QuoteIndexRoute
  '/staff/order/$id': typeof StaffOrderIdRoute
  '/staff/quote/$id': typeof StaffQuoteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/basket': typeof BasketRoute
  '/bulk-order': typeof BulkOrderRoute
  '/categories': typeof CategoriesRoute
  '/order-submitted': typeof OrderSubmittedRoute
  '/preview-access': typeof PreviewAccessRoute
  '/quote-submitted': typeof QuoteSubmittedRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/staff-login': typeof StaffLoginRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/pricing': typeof AccountPricingRoute
  '/account/users': typeof AccountUsersRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/fixture-shopify-login': typeof DevFixtureShopifyLoginRoute
  '/dev/shopify-health': typeof DevShopifyHealthRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$sku': typeof ProductSkuRoute
  '/quote/$id': typeof QuoteIdRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/quotes': typeof StaffQuotesRoute
  '/account/': typeof AccountIndexRoute
  '/quote/': typeof QuoteIndexRoute
  '/staff/order/$id': typeof StaffOrderIdRoute
  '/staff/quote/$id': typeof StaffQuoteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/auth-callback'
    | '/basket'
    | '/bulk-order'
    | '/categories'
    | '/order-submitted'
    | '/preview-access'
    | '/quote-submitted'
    | '/register'
    | '/search'
    | '/staff-login'
    | '/account/orders'
    | '/account/pricing'
    | '/account/users'
    | '/category/$slug'
    | '/checkout/$id'
    | '/dev/components'
    | '/dev/fixture-shopify-login'
    | '/dev/shopify-health'
    | '/order/$id'
    | '/product/$sku'
    | '/quote/$id'
    | '/staff/orders'
    | '/staff/quotes'
    | '/account/'
    | '/quote/'
    | '/staff/order/$id'
    | '/staff/quote/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/basket'
    | '/bulk-order'
    | '/categories'
    | '/order-submitted'
    | '/preview-access'
    | '/quote-submitted'
    | '/register'
    | '/search'
    | '/staff-login'
    | '/account/orders'
    | '/account/pricing'
    | '/account/users'
    | '/category/$slug'
    | '/checkout/$id'
    | '/dev/components'
    | '/dev/fixture-shopify-login'
    | '/dev/shopify-health'
    | '/order/$id'
    | '/product/$sku'
    | '/quote/$id'
    | '/staff/orders'
    | '/staff/quotes'
    | '/account'
    | '/quote'
    | '/staff/order/$id'
    | '/staff/quote/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/auth-callback'
    | '/basket'
    | '/bulk-order'
    | '/categories'
    | '/order-submitted'
    | '/preview-access'
    | '/quote-submitted'
    | '/register'
    | '/search'
    | '/staff-login'
    | '/account/orders'
    | '/account/pricing'
    | '/account/users'
    | '/category/$slug'
    | '/checkout/$id'
    | '/dev/components'
    | '/dev/fixture-shopify-login'
    | '/dev/shopify-health'
    | '/order/$id'
    | '/product/$sku'
    | '/quote/$id'
    | '/staff/orders'
    | '/staff/quotes'
    | '/account/'
    | '/quote/'
    | '/staff/order/$id'
    | '/staff/quote/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BasketRoute: typeof BasketRoute
  BulkOrderRoute: typeof BulkOrderRoute
  CategoriesRoute: typeof CategoriesRoute
  OrderSubmittedRoute: typeof OrderSubmittedRoute
  PreviewAccessRoute: typeof PreviewAccessRoute
  QuoteSubmittedRoute: typeof QuoteSubmittedRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  StaffLoginRoute: typeof StaffLoginRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  DevComponentsRoute: typeof DevComponentsRoute
  DevFixtureShopifyLoginRoute: typeof DevFixtureShopifyLoginRoute
  DevShopifyHealthRoute: typeof DevShopifyHealthRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSkuRoute: typeof ProductSkuRoute
  QuoteIdRoute: typeof QuoteIdRoute
  StaffOrdersRoute: typeof StaffOrdersRoute
  StaffQuotesRoute: typeof StaffQuotesRoute
  QuoteIndexRoute: typeof QuoteIndexRoute
  StaffOrderIdRoute: typeof StaffOrderIdRoute
  StaffQuoteIdRoute: typeof StaffQuoteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-order': {
      id: '/bulk-order'
      path: '/bulk-order'
      fullPath: '/bulk-order'
      preLoaderRoute: typeof BulkOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-submitted': {
      id: '/order-submitted'
      path: '/order-submitted'
      fullPath: '/order-submitted'
      preLoaderRoute: typeof OrderSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview-access': {
      id: '/preview-access'
      path: '/preview-access'
      fullPath: '/preview-access'
      preLoaderRoute: typeof PreviewAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote-submitted': {
      id: '/quote-submitted'
      path: '/quote-submitted'
      fullPath: '/quote-submitted'
      preLoaderRoute: typeof QuoteSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/pricing': {
      id: '/account/pricing'
      path: '/pricing'
      fullPath: '/account/pricing'
      preLoaderRoute: typeof AccountPricingRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/users': {
      id: '/account/users'
      path: '/users'
      fullPath: '/account/users'
      preLoaderRoute: typeof AccountUsersRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/fixture-shopify-login': {
      id: '/dev/fixture-shopify-login'
      path: '/dev/fixture-shopify-login'
      fullPath: '/dev/fixture-shopify-login'
      preLoaderRoute: typeof DevFixtureShopifyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/shopify-health': {
      id: '/dev/shopify-health'
      path: '/dev/shopify-health'
      fullPath: '/dev/shopify-health'
      preLoaderRoute: typeof DevShopifyHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$sku': {
      id: '/product/$sku'
      path: '/product/$sku'
      fullPath: '/product/$sku'
      preLoaderRoute: typeof ProductSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/': {
      id: '/quote/'
      path: '/quote'
      fullPath: '/quote/'
      preLoaderRoute: typeof QuoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$id': {
      id: '/quote/$id'
      path: '/quote/$id'
      fullPath: '/quote/$id'
      preLoaderRoute: typeof QuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/orders': {
      id: '/staff/orders'
      path: '/staff/orders'
      fullPath: '/staff/orders'
      preLoaderRoute: typeof StaffOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/quotes': {
      id: '/staff/quotes'
      path: '/staff/quotes'
      fullPath: '/staff/quotes'
      preLoaderRoute: typeof StaffQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/order/$id': {
      id: '/staff/order/$id'
      path: '/staff/order/$id'
      fullPath: '/staff/order/$id'
      preLoaderRoute: typeof StaffOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/quote/$id': {
      id: '/staff/quote/$id'
      path: '/staff/quote/$id'
      fullPath: '/staff/quote/$id'
      preLoaderRoute: typeof StaffQuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountPricingRoute: typeof AccountPricingRoute
  AccountUsersRoute: typeof AccountUsersRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountOrdersRoute: AccountOrdersRoute,
  AccountPricingRoute: AccountPricingRoute,
  AccountUsersRoute: AccountUsersRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BasketRoute: BasketRoute,
  BulkOrderRoute: BulkOrderRoute,
  CategoriesRoute: CategoriesRoute,
  OrderSubmittedRoute: OrderSubmittedRoute,
  PreviewAccessRoute: PreviewAccessRoute,
  QuoteSubmittedRoute: QuoteSubmittedRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  StaffLoginRoute: StaffLoginRoute,
  CategorySlugRoute: CategorySlugRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  DevComponentsRoute: DevComponentsRoute,
  DevFixtureShopifyLoginRoute: DevFixtureShopifyLoginRoute,
  DevShopifyHealthRoute: DevShopifyHealthRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSkuRoute: ProductSkuRoute,
  QuoteIdRoute: QuoteIdRoute,
  StaffOrdersRoute: StaffOrdersRoute,
  StaffQuotesRoute: StaffQuotesRoute,
  QuoteIndexRoute: QuoteIndexRoute,
  StaffOrderIdRoute: StaffOrderIdRoute,
  StaffQuoteIdRoute: StaffQuoteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
