/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthCallbackRouteImport } from './routes/auth-callback'
import { Route as BasketRouteImport } from './routes/basket'
import { Route as BulkOrderRouteImport } from './routes/bulk-order'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as HowToOrderRouteImport } from './routes/how-to-order'
import { Route as OrderSubmittedRouteImport } from './routes/order-submitted'
import { Route as QuoteSubmittedRouteImport } from './routes/quote-submitted'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StaffLoginRouteImport } from './routes/staff-login'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as AccountPricingRouteImport } from './routes/account/pricing'
import { Route as AccountReturnsRouteImport } from './routes/account/returns'
import { Route as AccountUsersRouteImport } from './routes/account/users'
import { Route as ApiCatalogueRouteImport } from './routes/api/catalogue'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as CheckoutIdRouteImport } from './routes/checkout/$id'
import { Route as DevComponentsRouteImport } from './routes/dev/components'
import { Route as DevFixtureShopifyLoginRouteImport } from './routes/dev/fixture-shopify-login'
import { Route as DevShopifyHealthRouteImport } from './routes/dev/shopify-health'
import { Route as OrderIdRouteImport } from './routes/order/$id'
import { Route as ProductSkuRouteImport } from './routes/product/$sku'
import { Route as QuoteIndexRouteImport } from './routes/quote/index'
import { Route as QuoteIdRouteImport } from './routes/quote/$id'
import { Route as ReturnsIndexRouteImport } from './routes/returns/index'
import { Route as ReturnsIdRouteImport } from './routes/returns/$id'
import { Route as StaffIndexRouteImport } from './routes/staff/index'
import { Route as StaffAccountsRouteImport } from './routes/staff/accounts'
import { Route as StaffOrdersRouteImport } from './routes/staff/orders'
import { Route as StaffQuotesRouteImport } from './routes/staff/quotes'
import { Route as StaffReturnsRouteImport } from './routes/staff/returns'
import { Route as StaffTeamRouteImport } from './routes/staff/team'
import { Route as SupportIndexRouteImport } from './routes/support/index'
import { Route as SupportIdRouteImport } from './routes/support/$id'
import { Route as StaffOrderIdRouteImport } from './routes/staff/order/$id'
import { Route as StaffQuoteIdRouteImport } from './routes/staff/quote/$id'
import { Route as StaffReturnIdRouteImport } from './routes/staff/return/$id'
import { Route as StaffSupportIndexRouteImport } from './routes/staff/support/index'
import { Route as StaffSupportIdRouteImport } from './routes/staff/support/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth-callback',
  path: '/auth-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BasketRoute = BasketRouteImport.update({
  id: '/basket',
  path: '/basket',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkOrderRoute = BulkOrderRouteImport.update({
  id: '/bulk-order',
  path: '/bulk-order',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToOrderRoute = HowToOrderRouteImport.update({
  id: '/how-to-order',
  path: '/how-to-order',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSubmittedRoute = OrderSubmittedRouteImport.update({
  id: '/order-submitted',
  path: '/order-submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteSubmittedRoute = QuoteSubmittedRouteImport.update({
  id: '/quote-submitted',
  path: '/quote-submitted',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff-login',
  path: '/staff-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountPricingRoute = AccountPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountReturnsRoute = AccountReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountUsersRoute = AccountUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AccountRouteRoute,
} as any)
const ApiCatalogueRoute = ApiCatalogueRouteImport.update({
  id: '/api/catalogue',
  path: '/api/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const DevFixtureShopifyLoginRoute = DevFixtureShopifyLoginRouteImport.update({
  id: '/dev/fixture-shopify-login',
  path: '/dev/fixture-shopify-login',
  getParentRoute: () => rootRouteImport,
} as any)
const DevShopifyHealthRoute = DevShopifyHealthRouteImport.update({
  id: '/dev/shopify-health',
  path: '/dev/shopify-health',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSkuRoute = ProductSkuRouteImport.update({
  id: '/product/$sku',
  path: '/product/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIndexRoute = QuoteIndexRouteImport.update({
  id: '/quote/',
  path: '/quote/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteIdRoute = QuoteIdRouteImport.update({
  id: '/quote/$id',
  path: '/quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsIndexRoute = ReturnsIndexRouteImport.update({
  id: '/returns/',
  path: '/returns/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsIdRoute = ReturnsIdRouteImport.update({
  id: '/returns/$id',
  path: '/returns/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAccountsRoute = StaffAccountsRouteImport.update({
  id: '/staff/accounts',
  path: '/staff/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffOrdersRoute = StaffOrdersRouteImport.update({
  id: '/staff/orders',
  path: '/staff/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffQuotesRoute = StaffQuotesRouteImport.update({
  id: '/staff/quotes',
  path: '/staff/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReturnsRoute = StaffReturnsRouteImport.update({
  id: '/staff/returns',
  path: '/staff/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffTeamRoute = StaffTeamRouteImport.update({
  id: '/staff/team',
  path: '/staff/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIndexRoute = SupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportIdRoute = SupportIdRouteImport.update({
  id: '/support/$id',
  path: '/support/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffOrderIdRoute = StaffOrderIdRouteImport.update({
  id: '/staff/order/$id',
  path: '/staff/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffQuoteIdRoute = StaffQuoteIdRouteImport.update({
  id: '/staff/quote/$id',
  path: '/staff/quote/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffReturnIdRoute = StaffReturnIdRouteImport.update({
  id: '/staff/return/$id',
  path: '/staff/return/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSupportIndexRoute = StaffSupportIndexRouteImport.update({
  id: '/staff/support/',
  path: '/staff/support/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffSupportIdRoute = StaffSupportIdRouteImport.update({
  id: '/staff/support/$id',
  path: '/staff/support/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/basket': typeof BasketRoute
  '/bulk-order': typeof BulkOrderRoute
  '/categories': typeof CategoriesRoute
  '/how-to-order': typeof HowToOrderRoute
  '/order-submitted': typeof OrderSubmittedRoute
  '/quote-submitted': typeof QuoteSubmittedRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/staff-login': typeof StaffLoginRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/pricing': typeof AccountPricingRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/users': typeof AccountUsersRoute
  '/api/catalogue': typeof ApiCatalogueRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/fixture-shopify-login': typeof DevFixtureShopifyLoginRoute
  '/dev/shopify-health': typeof DevShopifyHealthRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$sku': typeof ProductSkuRoute
  '/quote/$id': typeof QuoteIdRoute
  '/returns/$id': typeof ReturnsIdRoute
  '/staff/accounts': typeof StaffAccountsRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/quotes': typeof StaffQuotesRoute
  '/staff/returns': typeof StaffReturnsRoute
  '/staff/team': typeof StaffTeamRoute
  '/support/$id': typeof SupportIdRoute
  '/account/': typeof AccountIndexRoute
  '/quote/': typeof QuoteIndexRoute
  '/returns/': typeof ReturnsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/support/': typeof SupportIndexRoute
  '/staff/order/$id': typeof StaffOrderIdRoute
  '/staff/quote/$id': typeof StaffQuoteIdRoute
  '/staff/return/$id': typeof StaffReturnIdRoute
  '/staff/support/$id': typeof StaffSupportIdRoute
  '/staff/support/': typeof StaffSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/basket': typeof BasketRoute
  '/bulk-order': typeof BulkOrderRoute
  '/categories': typeof CategoriesRoute
  '/how-to-order': typeof HowToOrderRoute
  '/order-submitted': typeof OrderSubmittedRoute
  '/quote-submitted': typeof QuoteSubmittedRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/staff-login': typeof StaffLoginRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/pricing': typeof AccountPricingRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/users': typeof AccountUsersRoute
  '/api/catalogue': typeof ApiCatalogueRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/fixture-shopify-login': typeof DevFixtureShopifyLoginRoute
  '/dev/shopify-health': typeof DevShopifyHealthRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$sku': typeof ProductSkuRoute
  '/quote/$id': typeof QuoteIdRoute
  '/returns/$id': typeof ReturnsIdRoute
  '/staff/accounts': typeof StaffAccountsRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/quotes': typeof StaffQuotesRoute
  '/staff/returns': typeof StaffReturnsRoute
  '/staff/team': typeof StaffTeamRoute
  '/support/$id': typeof SupportIdRoute
  '/account': typeof AccountIndexRoute
  '/quote': typeof QuoteIndexRoute
  '/returns': typeof ReturnsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/support': typeof SupportIndexRoute
  '/staff/order/$id': typeof StaffOrderIdRoute
  '/staff/quote/$id': typeof StaffQuoteIdRoute
  '/staff/return/$id': typeof StaffReturnIdRoute
  '/staff/support/$id': typeof StaffSupportIdRoute
  '/staff/support': typeof StaffSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/auth-callback': typeof AuthCallbackRoute
  '/basket': typeof BasketRoute
  '/bulk-order': typeof BulkOrderRoute
  '/categories': typeof CategoriesRoute
  '/how-to-order': typeof HowToOrderRoute
  '/order-submitted': typeof OrderSubmittedRoute
  '/quote-submitted': typeof QuoteSubmittedRoute
  '/register': typeof RegisterRoute
  '/search': typeof SearchRoute
  '/staff-login': typeof StaffLoginRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/pricing': typeof AccountPricingRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/users': typeof AccountUsersRoute
  '/api/catalogue': typeof ApiCatalogueRoute
  '/category/$slug': typeof CategorySlugRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/dev/fixture-shopify-login': typeof DevFixtureShopifyLoginRoute
  '/dev/shopify-health': typeof DevShopifyHealthRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$sku': typeof ProductSkuRoute
  '/quote/$id': typeof QuoteIdRoute
  '/returns/$id': typeof ReturnsIdRoute
  '/staff/accounts': typeof StaffAccountsRoute
  '/staff/orders': typeof StaffOrdersRoute
  '/staff/quotes': typeof StaffQuotesRoute
  '/staff/returns': typeof StaffReturnsRoute
  '/staff/team': typeof StaffTeamRoute
  '/support/$id': typeof SupportIdRoute
  '/account/': typeof AccountIndexRoute
  '/quote/': typeof QuoteIndexRoute
  '/returns/': typeof ReturnsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/support/': typeof SupportIndexRoute
  '/staff/order/$id': typeof StaffOrderIdRoute
  '/staff/quote/$id': typeof StaffQuoteIdRoute
  '/staff/return/$id': typeof StaffReturnIdRoute
  '/staff/support/$id': typeof StaffSupportIdRoute
  '/staff/support/': typeof StaffSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/auth-callback'
    | '/basket'
    | '/bulk-order'
    | '/categories'
    | '/how-to-order'
    | '/order-submitted'
    | '/quote-submitted'
    | '/register'
    | '/search'
    | '/staff-login'
    | '/account/orders'
    | '/account/pricing'
    | '/account/returns'
    | '/account/users'
    | '/api/catalogue'
    | '/category/$slug'
    | '/checkout/$id'
    | '/dev/components'
    | '/dev/fixture-shopify-login'
    | '/dev/shopify-health'
    | '/order/$id'
    | '/product/$sku'
    | '/quote/$id'
    | '/returns/$id'
    | '/staff/accounts'
    | '/staff/orders'
    | '/staff/quotes'
    | '/staff/returns'
    | '/staff/team'
    | '/support/$id'
    | '/account/'
    | '/quote/'
    | '/returns/'
    | '/staff/'
    | '/support/'
    | '/staff/order/$id'
    | '/staff/quote/$id'
    | '/staff/return/$id'
    | '/staff/support/$id'
    | '/staff/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auth-callback'
    | '/basket'
    | '/bulk-order'
    | '/categories'
    | '/how-to-order'
    | '/order-submitted'
    | '/quote-submitted'
    | '/register'
    | '/search'
    | '/staff-login'
    | '/account/orders'
    | '/account/pricing'
    | '/account/returns'
    | '/account/users'
    | '/api/catalogue'
    | '/category/$slug'
    | '/checkout/$id'
    | '/dev/components'
    | '/dev/fixture-shopify-login'
    | '/dev/shopify-health'
    | '/order/$id'
    | '/product/$sku'
    | '/quote/$id'
    | '/returns/$id'
    | '/staff/accounts'
    | '/staff/orders'
    | '/staff/quotes'
    | '/staff/returns'
    | '/staff/team'
    | '/support/$id'
    | '/account'
    | '/quote'
    | '/returns'
    | '/staff'
    | '/support'
    | '/staff/order/$id'
    | '/staff/quote/$id'
    | '/staff/return/$id'
    | '/staff/support/$id'
    | '/staff/support'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/auth-callback'
    | '/basket'
    | '/bulk-order'
    | '/categories'
    | '/how-to-order'
    | '/order-submitted'
    | '/quote-submitted'
    | '/register'
    | '/search'
    | '/staff-login'
    | '/account/orders'
    | '/account/pricing'
    | '/account/returns'
    | '/account/users'
    | '/api/catalogue'
    | '/category/$slug'
    | '/checkout/$id'
    | '/dev/components'
    | '/dev/fixture-shopify-login'
    | '/dev/shopify-health'
    | '/order/$id'
    | '/product/$sku'
    | '/quote/$id'
    | '/returns/$id'
    | '/staff/accounts'
    | '/staff/orders'
    | '/staff/quotes'
    | '/staff/returns'
    | '/staff/team'
    | '/support/$id'
    | '/account/'
    | '/quote/'
    | '/returns/'
    | '/staff/'
    | '/support/'
    | '/staff/order/$id'
    | '/staff/quote/$id'
    | '/staff/return/$id'
    | '/staff/support/$id'
    | '/staff/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  BasketRoute: typeof BasketRoute
  BulkOrderRoute: typeof BulkOrderRoute
  CategoriesRoute: typeof CategoriesRoute
  HowToOrderRoute: typeof HowToOrderRoute
  OrderSubmittedRoute: typeof OrderSubmittedRoute
  QuoteSubmittedRoute: typeof QuoteSubmittedRoute
  RegisterRoute: typeof RegisterRoute
  SearchRoute: typeof SearchRoute
  StaffLoginRoute: typeof StaffLoginRoute
  ApiCatalogueRoute: typeof ApiCatalogueRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  DevComponentsRoute: typeof DevComponentsRoute
  DevFixtureShopifyLoginRoute: typeof DevFixtureShopifyLoginRoute
  DevShopifyHealthRoute: typeof DevShopifyHealthRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSkuRoute: typeof ProductSkuRoute
  QuoteIdRoute: typeof QuoteIdRoute
  ReturnsIdRoute: typeof ReturnsIdRoute
  StaffAccountsRoute: typeof StaffAccountsRoute
  StaffOrdersRoute: typeof StaffOrdersRoute
  StaffQuotesRoute: typeof StaffQuotesRoute
  StaffReturnsRoute: typeof StaffReturnsRoute
  StaffTeamRoute: typeof StaffTeamRoute
  SupportIdRoute: typeof SupportIdRoute
  QuoteIndexRoute: typeof QuoteIndexRoute
  ReturnsIndexRoute: typeof ReturnsIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  SupportIndexRoute: typeof SupportIndexRoute
  StaffOrderIdRoute: typeof StaffOrderIdRoute
  StaffQuoteIdRoute: typeof StaffQuoteIdRoute
  StaffReturnIdRoute: typeof StaffReturnIdRoute
  StaffSupportIdRoute: typeof StaffSupportIdRoute
  StaffSupportIndexRoute: typeof StaffSupportIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth-callback': {
      id: '/auth-callback'
      path: '/auth-callback'
      fullPath: '/auth-callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basket': {
      id: '/basket'
      path: '/basket'
      fullPath: '/basket'
      preLoaderRoute: typeof BasketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk-order': {
      id: '/bulk-order'
      path: '/bulk-order'
      fullPath: '/bulk-order'
      preLoaderRoute: typeof BulkOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-order': {
      id: '/how-to-order'
      path: '/how-to-order'
      fullPath: '/how-to-order'
      preLoaderRoute: typeof HowToOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-submitted': {
      id: '/order-submitted'
      path: '/order-submitted'
      fullPath: '/order-submitted'
      preLoaderRoute: typeof OrderSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote-submitted': {
      id: '/quote-submitted'
      path: '/quote-submitted'
      fullPath: '/quote-submitted'
      preLoaderRoute: typeof QuoteSubmittedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-login': {
      id: '/staff-login'
      path: '/staff-login'
      fullPath: '/staff-login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/pricing': {
      id: '/account/pricing'
      path: '/pricing'
      fullPath: '/account/pricing'
      preLoaderRoute: typeof AccountPricingRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/returns': {
      id: '/account/returns'
      path: '/returns'
      fullPath: '/account/returns'
      preLoaderRoute: typeof AccountReturnsRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/users': {
      id: '/account/users'
      path: '/users'
      fullPath: '/account/users'
      preLoaderRoute: typeof AccountUsersRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/api/catalogue': {
      id: '/api/catalogue'
      path: '/api/catalogue'
      fullPath: '/api/catalogue'
      preLoaderRoute: typeof ApiCatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/fixture-shopify-login': {
      id: '/dev/fixture-shopify-login'
      path: '/dev/fixture-shopify-login'
      fullPath: '/dev/fixture-shopify-login'
      preLoaderRoute: typeof DevFixtureShopifyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/shopify-health': {
      id: '/dev/shopify-health'
      path: '/dev/shopify-health'
      fullPath: '/dev/shopify-health'
      preLoaderRoute: typeof DevShopifyHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$sku': {
      id: '/product/$sku'
      path: '/product/$sku'
      fullPath: '/product/$sku'
      preLoaderRoute: typeof ProductSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/': {
      id: '/quote/'
      path: '/quote'
      fullPath: '/quote/'
      preLoaderRoute: typeof QuoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote/$id': {
      id: '/quote/$id'
      path: '/quote/$id'
      fullPath: '/quote/$id'
      preLoaderRoute: typeof QuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/': {
      id: '/returns/'
      path: '/returns'
      fullPath: '/returns/'
      preLoaderRoute: typeof ReturnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns/$id': {
      id: '/returns/$id'
      path: '/returns/$id'
      fullPath: '/returns/$id'
      preLoaderRoute: typeof ReturnsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/accounts': {
      id: '/staff/accounts'
      path: '/staff/accounts'
      fullPath: '/staff/accounts'
      preLoaderRoute: typeof StaffAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/orders': {
      id: '/staff/orders'
      path: '/staff/orders'
      fullPath: '/staff/orders'
      preLoaderRoute: typeof StaffOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/quotes': {
      id: '/staff/quotes'
      path: '/staff/quotes'
      fullPath: '/staff/quotes'
      preLoaderRoute: typeof StaffQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/returns': {
      id: '/staff/returns'
      path: '/staff/returns'
      fullPath: '/staff/returns'
      preLoaderRoute: typeof StaffReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/team': {
      id: '/staff/team'
      path: '/staff/team'
      fullPath: '/staff/team'
      preLoaderRoute: typeof StaffTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/': {
      id: '/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof SupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support/$id': {
      id: '/support/$id'
      path: '/support/$id'
      fullPath: '/support/$id'
      preLoaderRoute: typeof SupportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/order/$id': {
      id: '/staff/order/$id'
      path: '/staff/order/$id'
      fullPath: '/staff/order/$id'
      preLoaderRoute: typeof StaffOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/quote/$id': {
      id: '/staff/quote/$id'
      path: '/staff/quote/$id'
      fullPath: '/staff/quote/$id'
      preLoaderRoute: typeof StaffQuoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/return/$id': {
      id: '/staff/return/$id'
      path: '/staff/return/$id'
      fullPath: '/staff/return/$id'
      preLoaderRoute: typeof StaffReturnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/support/': {
      id: '/staff/support/'
      path: '/staff/support'
      fullPath: '/staff/support/'
      preLoaderRoute: typeof StaffSupportIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/support/$id': {
      id: '/staff/support/$id'
      path: '/staff/support/$id'
      fullPath: '/staff/support/$id'
      preLoaderRoute: typeof StaffSupportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteRouteChildren {
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountPricingRoute: typeof AccountPricingRoute
  AccountReturnsRoute: typeof AccountReturnsRoute
  AccountUsersRoute: typeof AccountUsersRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountOrdersRoute: AccountOrdersRoute,
  AccountPricingRoute: AccountPricingRoute,
  AccountReturnsRoute: AccountReturnsRoute,
  AccountUsersRoute: AccountUsersRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  BasketRoute: BasketRoute,
  BulkOrderRoute: BulkOrderRoute,
  CategoriesRoute: CategoriesRoute,
  HowToOrderRoute: HowToOrderRoute,
  OrderSubmittedRoute: OrderSubmittedRoute,
  QuoteSubmittedRoute: QuoteSubmittedRoute,
  RegisterRoute: RegisterRoute,
  SearchRoute: SearchRoute,
  StaffLoginRoute: StaffLoginRoute,
  ApiCatalogueRoute: ApiCatalogueRoute,
  CategorySlugRoute: CategorySlugRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  DevComponentsRoute: DevComponentsRoute,
  DevFixtureShopifyLoginRoute: DevFixtureShopifyLoginRoute,
  DevShopifyHealthRoute: DevShopifyHealthRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSkuRoute: ProductSkuRoute,
  QuoteIdRoute: QuoteIdRoute,
  ReturnsIdRoute: ReturnsIdRoute,
  StaffAccountsRoute: StaffAccountsRoute,
  StaffOrdersRoute: StaffOrdersRoute,
  StaffQuotesRoute: StaffQuotesRoute,
  StaffReturnsRoute: StaffReturnsRoute,
  StaffTeamRoute: StaffTeamRoute,
  SupportIdRoute: SupportIdRoute,
  QuoteIndexRoute: QuoteIndexRoute,
  ReturnsIndexRoute: ReturnsIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  SupportIndexRoute: SupportIndexRoute,
  StaffOrderIdRoute: StaffOrderIdRoute,
  StaffQuoteIdRoute: StaffQuoteIdRoute,
  StaffReturnIdRoute: StaffReturnIdRoute,
  StaffSupportIdRoute: StaffSupportIdRoute,
  StaffSupportIndexRoute: StaffSupportIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
